apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-shop-server
  labels:
    app: product-shop-server
spec:
  replicas: 1  #il numero di server che girano (potrei anche avere 2 server di cui uno farà da recovery)
  selector:
    matchLabels:
      app: product-shop-server
  template:
    metadata:
      labels:
        app: product-shop-server
    spec:
      containers:  #dico in quale containers prendo l'immagine
      - name: product-shop-server
        image: matteo16/product-shop:server
        ports:
        - containerPort: 51234