name: Docker Build and Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push product-shop-client image
      run: |
        docker build -t product-shop-client ./product-shop-client
        docker tag product-shop-client ${{ secrets.DOCKER_USERNAME }}/product-shop:client
        docker push ${{ secrets.DOCKER_USERNAME }}/product-shop:client

    - name: Build and push product-shop-server image
      run: |
        docker build -t product-shop-server ./product-shop-server
        docker tag product-shop-server ${{ secrets.DOCKER_USERNAME }}/product-shop:server
        docker push ${{ secrets.DOCKER_USERNAME }}/product-shop:server

    - name: Build and push product-shop-session image
      run: |
        docker build -t product-shop-session ./product-shop-session
        docker tag product-shop-session ${{ secrets.DOCKER_USERNAME }}/product-shop:session
        docker push ${{ secrets.DOCKER_USERNAME }}/product-shop:session
